# Generated by Django 4.2.23 on 2025-09-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_course_options_alter_coursevideo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='benefits',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
