# Generated by Django 4.2.23 on 2025-09-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('course', models.CharField(blank=True, max_length=120)),
                ('story', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='success_stories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
