# Generated by Django 4.2.23 on 2025-09-27 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstory',
            name='testimonial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('success_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='success.successstory')),
            ],
        ),
    ]
