# Generated by Django 5.2.4 on 2025-08-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='name',
            field=models.CharField(default='Default Institution', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(default='TEMP000', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(default='Unknown Subject', max_length=100),
        ),
    ]
