# Generated by Django 5.2.4 on 2025-08-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_institution_teacher_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
