# Generated by Django 5.2.4 on 2025-08-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_student_age_student_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll_number',
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='STU000', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
